name: Integration Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Checkout OpenSearch Dashboard
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards
          repository: opensearch-project/OpenSearch-Dashboards
          fetch-depth: 0
      
      - name: Create plugins dir
        run: |
          cd ./OpenSearch-Dashboards
          mkdir -p plugins
      
      - name: Checkout OpenSearch Dashboard Security plugin
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/security-dashboards-plugin
          ref: ${{ github.ref }}

      - name: Get OpenSearch Dashboards version
        id: osd_version
        run: |
          echo "::set-output name=osd_version::$(jq -r '.opensearchDashboards.version' ./OpenSearch-Dashboards/plugins/security-dashboards-plugin/package.json)"
      
      - name: Get OpenSearch version
        id: opendistro_version
        run: |
          echo "::set-output name=opendistro_version::$(jq -r '.version' ./OpenSearch-Dashboards/plugins/security-dashboards-plugin/package.json | sed 's/[0-9]*$/0/')"
      
      - name: Run elasticsearch with plugin
        run: |
          cd ./OpenSearch-Dashboards/plugins/security-dashboards-plugin/.github/workflows
          docker-compose up -d

      - name: Use OpenSearch Dashboards release commit
        run: |
          cd ./OpenSearch-Dashboards
          # git checkout tags/v${{ steps.osd_version.outputs.osd_version }} -b v${{ steps.osd_version.outputs.osd_version }}
      
      - name: Get node and yarn versions
        id: versions
        run: |
          echo "::set-output name=node_version::$(cat ./OpenSearch-Dashboards/.node-version)"
          echo "::set-output name=yarn_version::$(jq -r '.engines.yarn' ./OpenSearch-Dashboards/package.json)"
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install correct yarn version for OpenSearch Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions.outputs.yarn_version }}
      
      - name: Bootstrap OpenSearch Dashboards
        run: |
          cd ./OpenSearch-Dashboards
          yarn osd bootstrap
      
      - name: Run integration test
        run: |
          cd ./OpenSearch-Dashboards/plugins/security-dashboards-plugin
          yarn test:jest_server --coverage
